name: Publish Docker image

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  workflow_run:
    workflows: [Releaser]
    types:
      - completed

# we want images in main to always build in-order, so main-latest always points
# at the latest one but it is ok to build 'latest' and 'release' in parallel,
# as it does not clash with 'main-*' ones
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  prepare_checkout:
    if: (
          github.repository == 'ipfs/bifrost-gateway'
          || github.event_name == 'workflow_dispatch'
        ) && (
          github.event_name != 'workflow_run'
          || github.event.workflow_run.conclusion == 'success'
        )
    name: Decide what ref to check out
    runs-on: ubuntu-latest
    outputs:
      ref: ${{ github.event_name != 'workflow_run' && github.ref || steps.releaser.outputs.version }}
    steps:
      - name: Inspect triggering Releaser workflow run
        id: releaser
        if: github.event_name == 'workflow_run'
        uses: protocol/.github/.github/actions/inspect-releaser@master
        with:
          artifacts-url: github.event.workflow_run.artifacts_url
  push_to_registry:
    needs: [prepare_checkout]
    if: needs.prepare_checkout.outputs.ref != ''
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ipfs/bifrost-gateway
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.prepare_checkout.outputs.ref }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Get tags
        id: tags
        run: |
          echo "value<<EOF" >> $GITHUB_OUTPUT
          ./docker/get-docker-tags.sh "$(date -u +%F)" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        shell: bash

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image and publish to Docker Hub
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
          context: .
          push: true
          file: ./Dockerfile
          tags: "${{ steps.tags.outputs.value }}"
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache to limit growth
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
